## reverse string 

In [1]:
def reverse_string(batch10):
    return batch10[::-1]
print(reverse_string("hello"))

olleh


In [6]:
# check palindrome
def is_palindrome(sentence):
    return sentence == sentence[::-1]
print(is_palindrome('madam'))

True


In [8]:
# count vowels 
#aeiou 
def count_vowels(text):
    count=0
    for i in text.lower():
        if i in 'aeiou':
            count+=1
    return count
print(count_vowels("Education"))

5


In [9]:
name = "Shyam Babu bind"

count = 0

for ch in name.lower():
  if ch in "aeiou":
    count += 1

print(count)

4


In [21]:
def chk_palindrome(s):
  if s == s[::-1]:
    print("It is palindrome")
  else:
    print("It is not palindrome")
s=input()
chk_palindrome(s)

 race care


It is not palindrome


In [15]:
def check(palli):
     if(palli[::-1] == palli):
          print("Palindrome")
     else:
          print("NOt palindrome")

palli = input("Enter the string")
check(palli)

Enter the string Madam


NOt palindrome


In [20]:
def check_palindrome():
  text = input("Enter a string: ")
  clean_text = text.replace(" ", "").lower()
   
  if clean_text == clean_text[::-1]:
    print("Yes it is palindrome")
  else:
    print("No it is not a palindrome")

check_palindrome()

Enter a string:  race car


Yes it is palindrome


In [ ]:
# check prime 
# with function and with function 
# take input
# H.W

In [22]:
# numpy 
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [23]:
import pandas as pd 

In [24]:
ai_batch = {
    'name': ['rajat', 'prabhat', 'abhishek','saumya'],
    'age': [86,59,45,97],
    'caurse': ['DS','DA','DE','AIML']
}
df=pd.DataFrame(ai_batch)
print(df)



       name  age caurse
0     rajat   86     DS
1   prabhat   59     DA
2  abhishek   45     DE
3    saumya   97   AIML


In [25]:
df

,name,age,caurse
0,rajat,86,DS
1,prabhat,59,DA
2,abhishek,45,DE
3,saumya,97,AIML


In [ ]:
naman,23,89.9,xyz

In [26]:
a=np.array([1,2,3,4])
a.dtype

dtype('int32')

In [27]:
b=np.array([[1,2,3],
            [4,5,6]])
b.shape


(2, 3)

In [28]:
b.size

6

In [29]:
b.sum()

21

In [30]:
b.mean()

3.5

In [31]:
b.max()

6

In [32]:
b.min()

1

In [35]:
x=np.array([50,60,70,80])
new_ar = x.reshape(2,3)
print(new_ar)

[[10 20 30]
 [40 50 60]]


In [37]:
x[2]

30

In [38]:
print(x[1:4])

[20 30 40]


In [39]:
print(x+70)

[ 80  90 100 110 120 130]


In [45]:
x=np.array([50,60,70,80])
y=np.array([10,20,30,40])
y+x

array([ 60,  80, 100, 120])

In [42]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
diagonal = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(np.diag(diagonal))
print(np.eye(3))

[1 5 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
def prime(num):
  if num <= 1:
    return False

  for i in range(2, num):
    if num % i == 0:
      return False

  return True

num = int(input("Enter a number: "))

if prime(num):
  print("Prime")
else:
  print("Not Prime")

Enter a number:  24


Not Prime
